### ISSUE TITLE
Integer input

### ISSUE THREAD

**Issue by kayz1** [manuelvanrijn/jquery-numeric_input#13]
Is there a way for input to accept only integers?

**Comment by wickedsp1d3r** [comment]
Hello,

Any updates on this?

**Comment by manuelvanrijn** [comment]
Sorry still haven't found the time to look into this. Any help/pullrequest are welcome

**Comment by lotestudio** [comment]
:)... Just set:
<pre>
    $("input.numeric_input_int").numeric_input({
            decimal:'',
            leadingZeroCheck: false
        });
</pre>
